package com.neuedu.dao;

import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;
import java.util.Set;


public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    List<Product> selectByPage(@Param("offset")Integer offset,@Param("length")Integer length);

    int selectTotalPageNo();

    int updateStatus(@Param("id")Integer id,@Param("status")Integer status);

    List<Product> searchProduct(@Param("productId") Integer productId,
                                @Param("keyword") String keyword);
    List<Product> searchProductByCategory(Integer categoryId);

    List<Product> searchByProductname(String searchText);

    List<Product> searchByCategorySet(@Param("integerSet")Set<Integer> integerSet);
}